/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function testSemaRelease(): Promise<void>
export function testSemaRequire(): Promise<void>
export function testShmWrite(input: string): Promise<void>
export function testShmRead(): string
export function show(): number
export function masterInit(workerNum: number): Promise<void>
export function workerInit(workerNum: number, index: number): void
export function processExit(): void
export function sendData(index: number, data: Buffer, n: number): void
export function callSafeFunc(callback: (...args: any[]) => any): void
export function callNodeFunc(): Promise<number>
export function init(): void
