/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function testSemaRelease(): Promise<void>
export function testSemaRequire(): Promise<void>
export function broadcast(input: string): Promise<void>
export function masterInit(workerNum: number): Promise<void>
export function workerInit(workerNum: number, index: number): void
export function processExit(): void
export function sendData(index: number, data: Buffer, n: number): void
export function regNodeFunc(callback: (result: string) => void): void
export function callNodeFunc(): Promise<number>
export function init(): void
